---
development:
  DB_FILENAME: db/local/dev.db
  CWB_TOKEN: CWB-TOKEN
  SESSION_SECRET: SESSION-SECRET
  REPOSTORE_PATH: repostore
  API_HOST: http://localhost:9092
  MBTI_QUESTION_MIN_ID: "1"
  MBTI_QUESTION_MAX_ID: "50"
test:
  DB_FILENAME: db/local/test.db
  CWB_TOKEN: CWB-TOKEN
  SESSION_SECRET: SESSION-SECRET
  REPOSTORE_PATH: repostore
  API_HOST: http://localhost:9092
  MBTI_QUESTION_MIN_ID: "1"
  MBTI_QUESTION_MAX_ID: "50"
