---
development:
  DB_FILENAME: db/local/dev.db
  CWB_TOKEN: CWB-TOKEN
  REPOSTORE_PATH: repostore
  API_HOST: http://localhost:9090
test:
  DB_FILENAME: db/local/test.db
  CWB_TOKEN: CWB-TOKEN
  REPOSTORE_PATH: repostore
  API_HOST: http://localhost:9090
